name: test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  gcc-reflection:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: mingw-w64-ucrt-x86_64-gcc
      - run: g++ --version
      - run: g++ -std=c++26 -freflection .github/relink/reflection.cpp -o reflection.exe && ./reflection.exe

  relink-msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-binutils mingw-w64-ucrt-x86_64-ruby
      - run: g++ -c .github/relink/main.cpp -o main.o && g++ -c .github/relink/undefined.cpp -o undefined.o
      - run: ruby bin/relink "g++" -o main.exe main.o undefined.o
      - run: ./main.exe || test $? -eq 42
